<?php

namespace AppBundle\Repository;

/**
 * ActivityGiodoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityGiodoRepository extends \Doctrine\ORM\EntityRepository
{
}
