<?php

namespace AppBundle\Repository;

/**
 * ActivityDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityDataRepository extends \Doctrine\ORM\EntityRepository
{
}
