<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ApplicationIpsRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ApplicationIpsRepository extends EntityRepository
{
//    public function findLastAgencyIps(Companies $companie)
//    {
//        return $this->getEntityManager()
//            ->createQuery(
//                'SELECT ai FROM AppBundle:ApplicationsIps ai
//                JOIN AppBundle:Companies c ON ai.
//                WHERE '
//            )
//            ->getResult();
//    }
}
