parameters:
#serwer testowy
    database_host: ods-vgp.test.unity.pl
    database_port: 3306
    database_name: gmind_esb
    database_user: deploy
    database_password: zaiD9ohhahWo

    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: ThisTokenIsNotSoSecretChangeIt


