# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.password_generator:
          class: AppBundle\Services\PasswordGenerator
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.password_generator_listiner:
        class: AppBundle\EventListener\PasswordGenerator
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    get_set_method_encoder:
        class: Symfony\Component\Serializer\Encoder\CsvEncoder
        arguments: [';']
        tags:
            - { name: serializer.encoder }

#    app.utils.csv_exporter:
#        class: AppBundle\Utils\CsvExport
#        arguments: ['@service_container']