# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.password_generator:
          class: AppBundle\Services\PasswordGenerator

    app.password_generator_listiner:
        class: AppBundle\EventListener\PasswordGenerator
        arguments: ['@app.password_generator']
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    get_set_method_encoder:
        class: Symfony\Component\Serializer\Encoder\CsvEncoder
        arguments: [';']
        tags:
            - { name: serializer.encoder }
