<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ApplicationsRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class BrandSetsRepository extends EntityRepository
{
    public function getNameA()
    {
        return $this->createQueryBuilder('b')->getFirstResult();
//            ->where('a.company = :company')
//            ->setParameter('company', $company->getId())
//            ->orderBy('a.id', 'DESC')
//            ->setMaxResults(1)
//            ->getQuery()
//            ->getSingleResult()
//            ;
    }
}
